# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        go-version: [ stable ]
        app: [ greetings, hello ]

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/${{ matrix.app }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache-dependency-path: src/${{ matrix.app }}/go.sum

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -json > TestResults-${{ matrix.app }}-${{ matrix.go-version }}.json

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: TestResults-${{ matrix.app }}-${{ matrix.go-version }}
        path: TestResults-${{ matrix.app }}-${{ matrix.go-version }}.json
